[package]
name = "dfns-sdk-rs-examples"
version = "0.1.0"
edition = "2024"

[dependencies]
dfns-sdk-rs = { version = "0.1.0" }
tokio = { version = "1.43", features = ["full"] }
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0" 